site_name: lijiankuan's Blog

theme:
  name: 'material'
  language: 'zh'
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/code.png'
  palette:
    primary: 'Deep Orange'
    accent: 'Amber'
  feature:
    tabs: false
  font:
    text: 'Noto Serif SC'
    code: 'Roboto Mono'
    
extra:
  search:
    language: 'ja'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
# Copyright
copyright: 'Copyright &copy; 2016 - 2019 lijiankuan'
